# This is a basic workflow to help you get started with Actions

name: Build and Publish Docusaurus Content for docs.neoagi.com

# Controls when the workflow will run
on:
  # Triggers the workflow on pull_request to release has been closed
  push:
    branches: [ 'release' ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  merged_release:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.NEOAGI_CODE_ARTIFACT_CI_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.NEOAGI_CODE_ARTIFACT_CI_ACCESS_KEY }}

    steps:
      - name: Init Workflow Variables
        run: |
            echo "TAG_NAME=$(echo ${{ github.ref_name }} | sed s/v// )" >> $GITHUB_ENV
            echo "SHORT_HASH=$(echo ${{ github.sha }} | cut -c 1-8 )" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install NPM Dependencies
        run: |
          npm update
        shell: bash

      - name: Build Documentation
        run: | 
          npm run build
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.NEOAGI_DOCUMENTATION_BUCKET_WRITE_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEOAGI_DOCUMENTATION_BUCKET_WRITE_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Push Build
        run: | 
          cd build
          aws s3 sync . ${{ vars.NEOAGI_DOCUMENTATION_BUCKET_URI }} --delete
        shell: bash
